<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListClients(){
        return $this->createQueryBuilder('c')
            ->select('c.id','c.firstname','c.lastname','c.created','c.avatar')
            ->orderBy('c.created','DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
